version: '3'

services:
  outline:
    image: outlinewiki/outline:0.85
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/var/lib/outline/data

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER=outline
      POSTGRES_PASSWORD=outlinepass
      POSTGRES_DB=outline
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
